# Enable logging
logger:
  #level: DEBUG

# Enable Home Assistant API
api:
  encryption:
    key: !secret esphome_encryption

ota:
  - platform: esphome

text_sensor:
  # ESPHome information
  - platform: version
    name: "ESPHome Version"
    hide_timestamp: true
