button:
  #  restart button
  - platform: restart
    name: Restart device

  # Factory Reset Switch from ESPHome v2022.09
  - platform: factory_reset
    name: Restart with Factory Default Settings
