# Author by airijia.com
# ESP32-CAM
# Lovelace camera card https://github.com/custom-cards/camera-card
# Video tutorial https://youtu.be/-towjof_ixU

substitutions:
  devicename: energymeter
  friendly_name: "Energy meter"
  comment: "Varmeforbrug"  

esphome:
  name: $devicename
  platform: ESP32
  board: esp32dev
  comment: $comment

# ESP32-CAM
esp32_camera:
  resolution: SVGA
  external_clock:
    pin: GPIO0
    frequency: 20MHz
  i2c_pins:
    sda: GPIO26
    scl: GPIO27
  data_pins: [GPIO5, GPIO18, GPIO19, GPIO21, GPIO36, GPIO39, GPIO34, GPIO35]
  vsync_pin: GPIO25
  href_pin: GPIO23
  pixel_clock_pin: GPIO22
  power_down_pin: GPIO32

  name: energy_meter_camera
  # ... Frame Settings

# Flashlight
output:
  - platform: gpio
    pin: GPIO4
    id: gpio_4
light:
  - platform: binary
    output: gpio_4
    name: $devicename light

packages:
  wifi: !include include/wifi.yaml
  basic: !include include/basic.yaml
    