substitutions:
  name: powerplug
  id: "5"
  comment: "HiHome Plug (wpp-16s) - Ledig"
  
  v1_in:  "0.0"
  v2_in:  "662.0"
  v3_in:  "674.9"
  v4_in:  "684.4"
  v5_in:  "690.5"
  v6_in:  "704.0"
  v1_out: "0.0"
  v2_out: "212.5"
  v3_out: "216.2"
  v4_out: "219.1"
  v5_out: "221.0" 
  v6_out: "222.4"

  w1_in:  "0.0"
  w2_in:  "4241.9"
  w3_in:  "7199.2"
  w4_in:  "10805.9"
  w1_out: "0.85"
  w2_out: "636.8"
  w3_out: "1082.8"
  w4_out: "1622.8"

  a1_in:  "0.0"
  a2_in:  "3.386"
  a3_in:  "5.386"
  a4_in:  "8.915"
  a1_out: "0.0100"
  a2_out: "2.9001"
  a3_out: "4.9931"
  a4_out: "7.6341"

packages:
  wifi: !include include/wifi.yaml
  basic: !include include/basic.yaml
  time: !include include/time.yaml
  powerplug: !include include/powerplug/powerplug.yaml
  
  #include led and relay outputs
  output: !include include/powerplug/output.yaml

  #enable to the button on the powerplug
  button: !include include/powerplug/button.yaml

  #set relay on at boot
  #boot: !include include/powerplug/boot_relay_on.yaml

  #set switch on at boot
  boot: !include include/powerplug/boot_switch_on.yaml
  