substitutions:
  name: powerplug
  id: "8"
  comment: "HiHome Plug (wpp-16s) - Køleskab - må ikke slukkes"
  
  v1_in:  "0.0"
  v2_in:  "666.7"
  v3_in:  "657.8"
  v4_in:  "673.0"
  v5_in:  "683.4"
  v6_in:  "686.8"
  v1_out: "0.0"
  v2_out: "219.1"
  v3_out: "216.2"
  v4_out: "211.0"
  v5_out: "212.5" 
  v6_out: "222.4"
  
  w1_in:  "0.0"
  w2_in:  "4042.3"
  w3_in:  "6872.3"
  w4_in:  "10318.8"
  w1_out: "0.85"
  w2_out: "634.4"
  w3_out: "1080.4"
  w4_out: "1620.4"

  a1_in:  "0.0"
  a2_in:  "3.300"
  a3_in:  "5.685"
  a4_in:  "8.708"
  a1_out: "0.010"
  a2_out: "2.8897"
  a3_out: "4.9827"
  a4_out: "7.6237"

packages:
  wifi: !include include/wifi.yaml
  basic: !include include/basic.yaml
  time: !include include/time.yaml
  powerplug: !include include/powerplug/powerplug.yaml
  
  #include led and relay outputs
  output: !include include/powerplug/output.yaml

  #enable to the button on the powerplug
  #button: !include include/powerplug/button.yaml

  #set relay on at boot
  boot: !include include/powerplug/boot_relay_on.yaml

  #set switch on at boot
  #boot: !include include/powerplug/boot_switch_on.yaml
  