substitutions:
  device_name: ultimatesensor-mini-1
  sensorname: ultimatesensor-mini-1
  friendly_name: UltimateSensor Mini
  ultimatesensor_mini_hardware_version: "V1-Complete"
  update_manifest_url: "https://smarthomeshop.github.io/ultimatesensor-mini/ultimatesensor-mini-complete-manifest.json"
  # LD2450 UART pins på USM hardware
  ld2450_tx_pin: GPIO13
  ld2450_rx_pin: GPIO14

packages:
  wifi: !include include/wifi.yaml
  basic: !include include/basic.yaml
  time: !include include/time.yaml
  ultimatesensor:
    url: https://github.com/martinheidemann/ultimatesensor-mini
    ref: main
    files: [ultimatesensor-mini-v1/ultimatesensor-mini-common.yaml]
  ld2450:
    url: https://github.com/martinheidemann/everything-presence-lite
    ref: main
    files: [common/ld2450-base.yaml]