substitutions:
  device_name: watermeterkit
  friendly_name: WaterMeterKit
  sensorname: WaterMeterKit

packages:
  wifi: !include include/wifi.yaml
  basic: !include include/basic.yaml
  time: !include include/time.yaml
  watermeter:
    url: https://github.com/martinheidemann/watermeterkit
    ref: main
    files: [watermeterkit-v1/base.yaml]
